// 页面
export const ADD_PAGE = 'ADD_PAGE'
export const SET_PAGE_ID = 'SET_PAGE_ID'
export const SET_PAGE_NAME = 'SET_PAGE_NAME'
export const SET_PAGE_BACKGROUND = 'SET_PAGE_BACKGROUND'
export const SORT_PAGE = 'SORT_PAGE'
export const DELETE_PAGE = 'DELETE_PAGE'
export const PAGE_ANIMATION = 'PAGE_ANIMATION'

// 组件
export const ADD_WIDGET = 'ADD_WIDGET'
export const SET_WIDGET_ID = 'SET_WIDGET_ID'
export const SET_WIDGET_NAME = 'SET_WIDGET_NAME'
export const SET_WIDGET_STYLE = 'SET_WIDGET_STYLE'
export const SET_WIDGET_POSITION = 'SET_WIDGET_POSITION'
export const ADD_WIDGET_ANIMATION = 'ADD_WIDGET_ANIMATION'
export const SET_WIDGET_ANIMATION = 'SET_WIDGET_ANIMATION'
export const DELETE_WIDGET_ANIMATION = 'DELETE_WIDGET_ANIMATION'
export const SET_WIDGET_STATE = 'SET_WIDGET_STATE'
export const DELETE_WIDGET = 'DELETE_WIDGET'
export const SORT_WIDGET = 'SORT_WIDGET'
export const COPY_WIDGET = 'COPY_WIDGET'
export const SET_TEXT_CONTENT = 'SET_TEXT_CONTENT'

// 资源
export const RESOURCE_TARGET = 'RESOURCE_TARGET'
export const DELETE_RESOURCE = 'DELETE_RESOURCE'
export const UPLOAD_RESOURCE = 'UPLOAD_RESOURCE'

// 用户
export const SET_PASSPORT = 'SET_PASSPORT'
export const SET_USER = 'SET_USER'
export const GET_USER = 'GET_USER'

// 项目
export const ADD_PROJECT = 'ADD_PROJECT'
export const SET_PROJECT = 'SET_PROJECT'
export const GET_PROJECT = 'GET_PROJECT'
export const SAVE_PROJECT = 'SAVE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const RESET_PROJECT = 'RESET_PROJECT'
export const SET_PROJECT_EXTENDS = 'SET_PROJECT_EXTENDS'

// 缓存列表
export const GET_CACHE_LIST = 'GET_CACHE_LIST'
export const SET_CACHE_LIST = 'SET_CACHE_LIST'
export const ADD_CACHE_LIST = 'ADD_CACHE_LIST'
export const UPDATE_CACHE_LIST = 'UPDATE_CACHE_LIST'
export const DELETE_CACHE_LIST = 'DELETE_CACHE_LIST'
export const RESET_CACHE_LIST = 'RESET_CACHE_LIST'